In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(2)


array([0.84011885, 0.41673919])

In [18]:
np.random.rand(5,5)

array([[0.68292356, 0.70051935, 0.36489352, 0.13450978, 0.47960852],
       [0.14105441, 0.338741  , 0.10548759, 0.62124932, 0.87562712],
       [0.99313342, 0.16771485, 0.39628956, 0.17624778, 0.18482324],
       [0.5509764 , 0.01312265, 0.48173568, 0.17891828, 0.03974538],
       [0.77614527, 0.10986616, 0.6535729 , 0.17683682, 0.32891272]])

In [19]:
np.random.randn(5,5)

array([[ 0.20740876, -0.32958854, -1.4509729 ,  0.38366708,  0.47659025],
       [-1.34196326,  0.30313066,  0.26649377,  1.23867918, -0.38008761],
       [-0.53098069,  0.73652684, -1.3966122 ,  0.47858911, -0.03182492],
       [ 1.84952845,  0.8764616 , -0.29439181,  0.58969599, -0.01780101],
       [ 0.23102323,  0.28243666,  0.76063512, -0.76890337,  1.7619096 ]])

In [21]:
 ar=np.random.randint(1,100,10)

In [22]:
print(ar)

[55 21 56 79 97 74 62 77 76 58]


In [24]:
arr=np.arange(25)

In [25]:
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
runarr.argmax()

6

In [28]:
argmin and min

NameError: name 'argmin' is not defined

In [29]:
arr.shape


(25,)

In [30]:
arr.reshape(1,25).shape

(1, 25)

In [31]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.dtype

dtype('int32')

In [34]:
arr=np.arange(0,10)

In [35]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [37]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [38]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [39]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [40]:
np.log(arr)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [42]:
arr=np.arange(0,11)

In [43]:
arr
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[0:5]=100

In [49]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [50]:
arr=np.arange(0,11)

In [51]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [52]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.fives(10)

AttributeError: module 'numpy' has no attribute 'fives'

In [59]:
arr[0:10]=5

In [60]:
arr

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 10])

In [61]:
arr=np.arange(10,81,2)

In [62]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [67]:
##runarr=np.random.randint(0,8,10)
matarr=np.arange(3,3)

array([], dtype=int32)

In [69]:
runarr=np.random.randint(0,8,10)
matarr=arr.arange(5,5)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [73]:
arr=np.arange(9)

In [76]:
runarr=np.random.randint(0,8,10)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
arr=np.arange(25)


In [78]:
runarr=np.random.randint(1,25,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arr[arr>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ssssss